"""Enumerations for the OpsPolicy domain."""
import enum


class EmployeeType(str, enum.Enum):
    EMPLOYEE = "EMPLOYEE"
    CONTRACTOR = "CONTRACTOR"
    VENDOR = "VENDOR"
    INTERN = "INTERN"


class Role(str, enum.Enum):
    EMPLOYEE = "EMPLOYEE"
    MANAGER = "MANAGER"
    DEPARTMENT_HEAD = "DEPARTMENT_HEAD"
    DATA_OWNER = "DATA_OWNER"
    SECURITY_REVIEWER = "SECURITY_REVIEWER"
    FINANCE_REVIEWER = "FINANCE_REVIEWER"
    COMPLIANCE_OFFICER = "COMPLIANCE_OFFICER"
    PLATFORM_ADMIN = "PLATFORM_ADMIN"


class UserStatus(str, enum.Enum):
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    OFFBOARDED = "OFFBOARDED"


class ResourceType(str, enum.Enum):
    DATASET = "DATASET"
    PRODUCTION_SERVICE = "PRODUCTION_SERVICE"
    ENVIRONMENT = "ENVIRONMENT"
    APPLICATION = "APPLICATION"
    VENDOR_CONTRACT = "VENDOR_CONTRACT"


class Criticality(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class Sensitivity(str, enum.Enum):
    PUBLIC = "PUBLIC"
    INTERNAL = "INTERNAL"
    CONFIDENTIAL = "CONFIDENTIAL"
    RESTRICTED = "RESTRICTED"


class PolicyType(str, enum.Enum):
    ACCESS = "ACCESS"
    DATA = "DATA"
    PROCUREMENT = "PROCUREMENT"
    SECURITY = "SECURITY"
    GENERAL = "GENERAL"


class PolicyStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    UNDER_REVIEW = "UNDER_REVIEW"
    PUBLISHED = "PUBLISHED"
    SUSPENDED = "SUSPENDED"
    ARCHIVED = "ARCHIVED"


class RequestType(str, enum.Enum):
    DATASET_ACCESS = "DATASET_ACCESS"
    PRODUCTION_ACCESS = "PRODUCTION_ACCESS"
    PURCHASE_APPROVAL = "PURCHASE_APPROVAL"


class RequestStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    EVALUATING = "EVALUATING"
    UNDER_REVIEW = "UNDER_REVIEW"
    PARTIALLY_APPROVED = "PARTIALLY_APPROVED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"
    PROVISIONING = "PROVISIONING"
    ACTIVE = "ACTIVE"
    EXPIRING = "EXPIRING"
    REVOKED = "REVOKED"
    REVOCATION_FAILED = "REVOCATION_FAILED"
    ESCALATED = "ESCALATED"
    CANCELLED = "CANCELLED"
    CLOSED = "CLOSED"


class RiskLevel(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class Decision(str, enum.Enum):
    AUTO_APPROVE = "AUTO_APPROVE"
    REQUIRES_APPROVAL = "REQUIRES_APPROVAL"
    REJECT = "REJECT"
    REQUIRES_EXCEPTION = "REQUIRES_EXCEPTION"


class ExecutionMode(str, enum.Enum):
    SEQUENTIAL = "SEQUENTIAL"
    PARALLEL = "PARALLEL"


class WorkflowStatus(str, enum.Enum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"


class StageStatus(str, enum.Enum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    REJECTED = "REJECTED"
    SKIPPED = "SKIPPED"


class ApprovalTaskStatus(str, enum.Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"
    DELEGATED = "DELEGATED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"


class ExceptionStatus(str, enum.Enum):
    REQUESTED = "REQUESTED"
    UNDER_REVIEW = "UNDER_REVIEW"
    APPROVED = "APPROVED"
    ACTIVE = "ACTIVE"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    REVOKED = "REVOKED"


class ProvisioningStatus(str, enum.Enum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    RETRYING = "RETRYING"


class RevocationStatus(str, enum.Enum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    ESCALATED = "ESCALATED"


class GrantType(str, enum.Enum):
    GRANT_DATASET_READ = "GRANT_DATASET_READ"
    GRANT_DATASET_EXPORT = "GRANT_DATASET_EXPORT"
    GRANT_PRODUCTION_READ = "GRANT_PRODUCTION_READ"
    GRANT_PRODUCTION_ADMIN = "GRANT_PRODUCTION_ADMIN"
    APPROVE_PURCHASE = "APPROVE_PURCHASE"


class AnalyticsJobType(str, enum.Enum):
    COMPLIANCE_REFRESH = "COMPLIANCE_REFRESH"
    POLICY_SIMULATION = "POLICY_SIMULATION"
    HISTORICAL_EXPORT = "HISTORICAL_EXPORT"


class AnalyticsJobStatus(str, enum.Enum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
