"""initial schema

Revision ID: f1c5f3211d3a
Revises: 
Create Date: 2026-08-03 15:59:49.538032
"""
from alembic import op
import sqlalchemy as sa
import app.db.types


revision = 'f1c5f3211d3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_jobs',
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.Enum('COMPLIANCE_REFRESH', 'POLICY_SIMULATION', 'HISTORICAL_EXPORT', name='analyticsjobtype'), nullable=False),
    sa.Column('external_job_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', name='analyticsjobstatus'), nullable=False),
    sa.Column('input_reference', sa.String(length=255), nullable=True),
    sa.Column('result_reference', sa.String(length=255), nullable=True),
    sa.Column('result_payload', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('completed_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('organisation_id', sa.String(length=36), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('previous_state', sa.String(length=64), nullable=True),
    sa.Column('new_state', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('request_id_header', sa.String(length=128), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('notification_type', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=255), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    op.create_table('organisations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_units',
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('head_user_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policies',
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('policy_type', sa.Enum('ACCESS', 'DATA', 'PROCUREMENT', 'SECURITY', 'GENERAL', name='policytype'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'UNDER_REVIEW', 'PUBLISHED', 'SUSPENDED', 'ARCHIVED', name='policystatus'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_from', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('effective_until', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('owner_user_id', sa.String(length=36), nullable=True),
    sa.Column('published_version_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resources',
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.Enum('DATASET', 'PRODUCTION_SERVICE', 'ENVIRONMENT', 'APPLICATION', 'VENDOR_CONTRACT', name='resourcetype'), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=True),
    sa.Column('criticality', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='criticality'), nullable=False),
    sa.Column('sensitivity', sa.Enum('PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED', name='sensitivity'), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departments',
    sa.Column('business_unit_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('head_user_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_unit_id'], ['business_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy_versions',
    sa.Column('policy_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('definition_json', sa.JSON(), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('department_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('manager_user_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('manager_id', sa.String(length=36), nullable=True),
    sa.Column('employee_type', sa.Enum('EMPLOYEE', 'CONTRACTOR', 'VENDOR', 'INTERN', name='employeetype'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('EMPLOYEE', 'MANAGER', 'DEPARTMENT_HEAD', 'DATA_OWNER', 'SECURITY_REVIEWER', 'FINANCE_REVIEWER', 'COMPLIANCE_OFFICER', 'PLATFORM_ADMIN', name='role'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'OFFBOARDED', name='userstatus'), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('requests',
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('request_type', sa.Enum('DATASET_ACCESS', 'PRODUCTION_ACCESS', 'PURCHASE_APPROVAL', name='requesttype'), nullable=False),
    sa.Column('requester_id', sa.String(length=36), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('business_justification', sa.Text(), nullable=True),
    sa.Column('request_payload', sa.JSON(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevel'), nullable=True),
    sa.Column('decision', sa.Enum('AUTO_APPROVE', 'REQUIRES_APPROVAL', 'REJECT', 'REQUIRES_EXCEPTION', name='decision'), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'EVALUATING', 'UNDER_REVIEW', 'PARTIALLY_APPROVED', 'APPROVED', 'REJECTED', 'CHANGES_REQUESTED', 'PROVISIONING', 'ACTIVE', 'EXPIRING', 'REVOKED', 'REVOCATION_FAILED', 'ESCALATED', 'CANCELLED', 'CLOSED', name='requeststatus'), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('submitted_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('approved_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('activated_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('expires_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('completed_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('access_grants',
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('grant_type', sa.Enum('GRANT_DATASET_READ', 'GRANT_DATASET_EXPORT', 'GRANT_PRODUCTION_READ', 'GRANT_PRODUCTION_ADMIN', 'APPROVE_PURCHASE', name='granttype'), nullable=False),
    sa.Column('provisioning_status', sa.Enum('PENDING', 'IN_PROGRESS', 'SUCCEEDED', 'FAILED', 'RETRYING', name='provisioningstatus'), nullable=False),
    sa.Column('revocation_status', sa.Enum('PENDING', 'IN_PROGRESS', 'SUCCEEDED', 'FAILED', 'ESCALATED', name='revocationstatus'), nullable=True),
    sa.Column('granted_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('expires_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('revoked_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('external_reference', sa.String(length=255), nullable=True),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', 'grant_type', 'resource_id', 'user_id', name='uq_grant_idempotency')
    )
    op.create_table('approval_workflows',
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'REJECTED', 'CANCELLED', name='workflowstatus'), nullable=False),
    sa.Column('current_stage', sa.Integer(), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy_evaluations',
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('policy_id', sa.String(length=36), nullable=False),
    sa.Column('policy_version_id', sa.String(length=36), nullable=False),
    sa.Column('matched', sa.Boolean(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('violations', sa.JSON(), nullable=False),
    sa.Column('required_actions', sa.JSON(), nullable=False),
    sa.Column('risk_contribution', sa.Integer(), nullable=False),
    sa.Column('evaluated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy_exceptions',
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('policy_id', sa.String(length=36), nullable=True),
    sa.Column('requested_by', sa.String(length=36), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('risk_description', sa.Text(), nullable=True),
    sa.Column('compensating_controls', sa.Text(), nullable=True),
    sa.Column('start_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('expires_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'UNDER_REVIEW', 'APPROVED', 'ACTIVE', 'REJECTED', 'EXPIRED', 'REVOKED', name='exceptionstatus'), nullable=False),
    sa.Column('approved_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('revoked_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_stages',
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('stage_number', sa.Integer(), nullable=False),
    sa.Column('execution_mode', sa.Enum('SEQUENTIAL', 'PARALLEL', name='executionmode'), nullable=False),
    sa.Column('minimum_approvals', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'REJECTED', 'SKIPPED', name='stagestatus'), nullable=False),
    sa.Column('deadline_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['approval_workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revocation_attempts',
    sa.Column('access_grant_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('completed_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('next_retry_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['access_grant_id'], ['access_grants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_tasks',
    sa.Column('approval_stage_id', sa.String(length=36), nullable=False),
    sa.Column('approver_user_id', sa.String(length=36), nullable=True),
    sa.Column('approver_role', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CHANGES_REQUESTED', 'DELEGATED', 'EXPIRED', 'CANCELLED', name='approvaltaskstatus'), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('assigned_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('acted_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('due_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('delegated_from_user_id', sa.String(length=36), nullable=True),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('last_operation_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approval_stage_id'], ['approval_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('approval_tasks')
    op.drop_table('revocation_attempts')
    op.drop_table('approval_stages')
    op.drop_table('policy_exceptions')
    op.drop_table('policy_evaluations')
    op.drop_table('approval_workflows')
    op.drop_table('access_grants')
    op.drop_table('requests')
    op.drop_table('users')
    op.drop_table('teams')
    op.drop_table('policy_versions')
    op.drop_table('departments')
    op.drop_table('resources')
    op.drop_table('policies')
    op.drop_table('business_units')
    op.drop_table('organisations')
    op.drop_table('notifications')
    op.drop_table('audit_events')
    op.drop_table('analytics_jobs')
    # ### end Alembic commands ###
